// <auto-generated />
using System;
using LRP.Players.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LRP.Players.Data.Migrations
{
    [DbContext(typeof(PlayerDbContext))]
    [Migration("20200506131346_ImprovedTestData")]
    partial class ImprovedTestData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LRP.Players.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Player");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountRef = "test@dcurrey.co.uk",
                            DateJoined = new DateTime(2020, 5, 6, 14, 13, 45, 664, DateTimeKind.Local).AddTicks(5858),
                            FirstName = "Test",
                            IsActive = true,
                            LastName = "user"
                        },
                        new
                        {
                            Id = 2,
                            AccountRef = "jsmith@dcurrey.co.uk",
                            DateJoined = new DateTime(2020, 5, 6, 14, 13, 45, 672, DateTimeKind.Local).AddTicks(9684),
                            FirstName = "John",
                            IsActive = true,
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 3,
                            AccountRef = "val@dcurrey.co.uk",
                            DateJoined = new DateTime(2020, 5, 6, 14, 13, 45, 672, DateTimeKind.Local).AddTicks(9747),
                            FirstName = "Valdemar",
                            IsActive = true,
                            LastName = "Karlsson"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
